### ISSUE TITLE
FileMeta without created property causes error

### ISSUE THREAD

**Issue by daniel-michel** [silverbulletmd/silverbullet#1014]
When I tried to use the `Batch Rename Prefix` command I got the error:
```
space.ts:220 Failed to convert fileMeta to attachmentMeta 
{name: '_plug/emoji.plug.js.map', contentType: 'application/json', lastModified: 1713450939716, perm: 'ro', size: -1}
 
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Ph (space.ts:216:43)
    at space.ts:104:12
    at Array.flatMap (<anonymous>)
    at kh.fetchAttachmentList (space.ts:101:48)
    at async space.listAttachments [as callback] (space.ts:24:14)
    at async d5.onMessage (worker_sandbox.ts:72:26)
```
The issue is that the `FileMeta` for the built in plugs does not have the `created` property.
<details>
<summary>The FileMeta items without the <code>created</code> property</summary>

```
[
	{
		"name": "_plug/tasks.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397505,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/share.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397450,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/editor.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397572,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/sync.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397374,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/emoji.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397311,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/plug-manager.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397459,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/markdown.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397450,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/federation.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397495,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/template.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397546,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/index.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397601,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/search.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397514,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/query.plug.js",
		"contentType": "application/javascript",
		"lastModified": 1722688397480,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/emoji.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939716,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/markdown.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939764,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/sync.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939764,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/template.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939808,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/search.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939764,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/share.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939708,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/plug-manager.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939748,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/federation.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939760,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/tasks.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939708,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/query.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939868,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/editor.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939840,
		"perm": "ro",
		"size": -1
	},
	{
		"name": "_plug/index.plug.js.map",
		"contentType": "application/json",
		"lastModified": 1713450939880,
		"perm": "ro",
		"size": -1
	}
]
```

</details>

This seems to be because it just is not added:
https://github.com/silverbulletmd/silverbullet/blob/102e6d10eb50d1fb54305c1fee56f53fa889b255/common/spaces/asset_bundle_space_primitives.ts#L12-L54

Adding `created: 0,` in the fetchFileList function fixed the issue for me (at least for batch renaming), however I am not sure if that is an acceptable solution?

**Comment by zefhemel** [comment]
What rename are you performing? I'd never expect anything from an asset bundle to be renamed.

**Comment by daniel-michel** [comment]
I think the actual problem is that, while `*.plug.js` is ignored `*.plug.js.map` is not
https://github.com/silverbulletmd/silverbullet/blob/102e6d10eb50d1fb54305c1fee56f53fa889b255/common/space.ts#L100-L107
Or that the plug.js.map files are generated in the first place?

**Comment by daniel-michel** [comment]
Although I think it would still make sense to add a `created` property to the files from the asset bundle since I feel like it can easily lead to more errors in the future when not all objects of type `FileMeta` have the `created` property even though the type suggest that they do have it.

**Comment by daniel-michel** [comment]
I deleted the `*.plug.js.map` files and they did not come back when rebuilding. That also fixed the initial issue I had. I am not sure how I managed to get them created.

**Comment by zefhemel** [comment]
I agree with adding created everywhere though. Will do.

**Comment by daniel-michel** [comment]
I figured out why I had the `*.plug.js.map` files. I ran `deno task plugs --debug` at some point which creates source maps.
