### ISSUE TITLE
Buttons on transclusions broken

### ISSUE THREAD

**Issue by felixr** [silverbulletmd/silverbullet#1047]
To reproduce:

1. Go to https://silverbullet.md/Transclusions
2.  Click bake, edit or reload button
3. Check console

Error in the console is:

```
system.ts:26 Uncaught Error: Invalid function name q
    at system.invokeFunction [as callback] (system.ts:26:15)
    at H5.syscall (system.ts:134:36)
    at H5.localSyscall (system.ts:108:17)
    at up.localSyscall (client_system.ts:221:24)
    at HTMLButtonElement.<anonymous> (markdown_widget.ts:269:38)
```

**Comment by zefhemel** [comment]
Usually simply reloading the page 2-3 times does it.
