### ISSUE TITLE
Renaming a note seemed to delete all content

### ISSUE THREAD

**Issue by Kwikxilver** [silverbulletmd/silverbullet#1067]
Hi there,

I've been using Silverbullet for a while now, selfhosting via Docker. I use it to have a web interface for my notes I can access from anywhere, and am really enjoying it.

I had a really frustrating issue this afternoon. I was editing a note where I'd written a story and decided to rename it when I was finished. Upon renaming the note, the web interface threw up an error and returned a blank page. I tried to navigate back to the old name, but it was also blank. I've checked my space folder and can't find the note there as a file at all.

This is my log from Docker when the issue happened. I've also attached my full log exported from the Docker console to this post. If there's any way to get my writing back, it'd be great if you could let me know as I had put quite a bit on there!

[_silverbullet_logs.txt](https://github.com/user-attachments/files/16786033/_silverbullet_logs.txt)

`Requested file The Genesis Loop.md
Requested file The Genesis Loop.md
Requested file Library/Core/Widget/Table of Contents.md
Requested file The Genesis Loop.md
Requested file SETTINGS.md
Requested file Time Agency: Genesis Loop.md
Error GETting file Time Agency: Genesis Loop.md Could not get meta for Time Agency: Genesis Loop.md
Requested file The Genesis Loop.md
Writing file Time Agency: Genesis Loop.md
Error while writing file Time Agency: Genesis Loop.md TypeError: Invalid argument (os error 22): open '/space/Time Agency: Genesis Loop.md'
    at async Object.open (ext:deno_fs/30_fs.js:633:15)
    at async ux.writeFile (file:///silverbullet.js:2369:256222)
    at async vX.writeFile (file:///silverbullet.js:65:3131)
    at async file:///silverbullet.js:2379:12599
    at async c (file:///silverbullet.js:26:4231)
    at async file:///silverbullet.js:26:11381
    at async c (file:///silverbullet.js:26:4231)
    at async c (file:///silverbullet.js:26:4231)
    at async c (file:///silverbullet.js:26:4231)
    at async file:///silverbullet.js:26:9763 {
  code: "EINVAL"
}
Write failed Error: Could not write Time Agency: Genesis Loop.md
    at ux.writeFile (file:///silverbullet.js:2369:256455)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async vX.writeFile (file:///silverbullet.js:65:3131)
    at async file:///silverbullet.js:2379:12599
    at async c (file:///silverbullet.js:26:4231)
    at async file:///silverbullet.js:26:11381
    at async c (file:///silverbullet.js:26:4231)
    at async c (file:///silverbullet.js:26:4231)
    at async c (file:///silverbullet.js:26:4231)
    at async file:///silverbullet.js:26:9763
Requested file Time Agency: Genesis Loop.md
Error GETting file Time Agency: Genesis Loop.md Not found
Requested file The Genesis Loop.md
Requested file Library/Core/Widget/Table of Contents.md
Requested file Library/Core/Widget/Linked Mentions.md
Requested file The Genesis Loop.md
Deleting file The Genesis Loop.md
Booting up worker for query
Requested file Time Agency: Genesis Loop.md
Error GETting file Time Agency: Genesis Loop.md Could not get meta for Time Agency: Genesis Loop.md
Requested file SETTINGS.md`

**Comment by zefhemel** [comment]
I'm sorry this happened. I don't know anything can be done here though to recover. I suspect the problem is the colon in the name although that should work on most operating systems. What os are you running this on?

**Comment by Kwikxilver** [comment]
It's okay - I've accepted I can't recover it now. I should have set up a backup system, which I have now done using Git! Thank you for your guide on the forums.

That said, it would be good if we can figure out how to stop this happening in future!

I was running Silverbullet through Docker. The bare metal machine is Ubuntu 22.04.04 LTS Jammy Jellyfish though. Does that help?

I don't know if this changes anything, but the actual space itself is stored on an external hard drive that's permanently mounted to the host machine. 

Let me know if you need any more info!

**Comment by zefhemel** [comment]
What type of filesystem is it you're mounting?

**Comment by LachlanStuart** [comment]
This has hit me a couple times as well. The common elements were: Running SilverBullet `2.4.1-0-g3e1f03b2` inside Docker, and performing a rename or delete on a file inside a symlinked directory. Suddenly the symlink vanishes and it looks like all the files in that area of the space have disappeared.

I was able to reproduce this with SilverBullet `2.6.1-0-g9f54b3a7-2026-04-11T12-34-12Z` running inside Docker, but not with SilverBullet+ running natively. 

While trying to test, I also saw a scary case where, likely due to an interaction with sync (I have SilverBullet+ syncing to the Dockerized instance), both the symlink and the destination directory were deleted. I haven't been able to reliably reproduce it though.

Simple repro steps for the symlink removal. Run in Docker:

```bash
mkdir /space/test1
touch /space/test1/foo.md
touch /space/test1/bar.md
ln -s /space/test1 /space/test2
```

Rename or delete `test2/bar` inside SilverBullet. Then wait or click around a bit - it seems like the file operations aren't applied immediately. The `/space/test2` symlink usually disappears after ~10s and a few page changes, causing that entire directory to disappear from the tree view.

**EDIT:** To answer the filesystem question: Outside Docker is a standard Ubuntu 24.04 ext4 partition. Inside Docker it appears as an overlayfs.

**Comment by zefhemel** [comment]
Think I found the issue. Will fix.

**Comment by LachlanStuart** [comment]
Thank you!
