### ISSUE TITLE
Builds don’t work on Windows

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#107]
It's generating absolute Windows path for the temporary file, which ESBuild apparently doesn't like, probably need to be translated to something more Unixy:

```
   1 │ import {bla} from "C:\Users\Zef\AppData\Local\Temp\efb0334f\file.ts";export default bla;
```

**Comment by zefhemel** [comment]
Update: apparently building SB in general doesn't work on Windows, also due to `./build_plugs.sh` not being Windows compatible.

**Comment by pm64** [comment]
For reference, here's the current build output on Windows for 8d3688b2fd6308c5f115ebfff4cac40cb3ffe08c:

```
PS D:\temp\silverbullet-main> deno.exe task build
Task build deno run -A --unstable --check build_plugs.ts && deno run -A --unstable --check build.ts
Check file:///D:/temp/silverbullet-main/build_plugs.ts
Building [
  "D:\\temp\\silverbullet-main\\plugs\\collab\\collab.plug.yaml",
  "D:\\temp\\silverbullet-main\\plugs\\core\\core.plug.yaml",
  "D:\\temp\\silverbullet-main\\plugs\\directive\\directive.plug.yaml",
  "D:\\temp\\silverbullet-main\\plugs\\emoji\\emoji.plug.yaml",
  "D:\\temp\\silverbullet-main\\plugs\\markdown\\markdown.plug.yaml",
  "D:\\temp\\silverbullet-main\\plugs\\plugmd\\plugmd.plug.yaml",
  "D:\\temp\\silverbullet-main\\plugs\\share\\share.plug.yaml",
  "D:\\temp\\silverbullet-main\\plugs\\tasks\\tasks.plug.yaml"
]
Caching plug https://get.silverbullet.md/global.plug.json to C:\Users\User\AppData\Local\plugos
Caching plug https://get.silverbullet.md/global.plug.json to C:\Users\User\AppData\Local\plugos
Caching plug https://get.silverbullet.md/global.plug.json to C:\Users\User\AppData\Local\plugos
Caching plug https://get.silverbullet.md/global.plug.json to C:\Users\User\AppData\Local\plugos
Caching plug https://get.silverbullet.md/global.plug.json to C:\Users\User\AppData\Local\plugos
Caching plug https://get.silverbullet.md/global.plug.json to C:\Users\User\AppData\Local\plugos
Caching plug https://get.silverbullet.md/global.plug.json to C:\Users\User\AppData\Local\plugos
✘ [ERROR] [plugin deno] The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/97f7a089.ts:1:9

✘ [ERROR] [plugin deno] The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/88770189.ts:1:9

Error building D:\temp\silverbullet-main\plugs\plugmd\plugmd.plug.yaml: Error: Build failed with 1 error:
error: The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/97f7a089.ts:1:9
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.54/mod.js:1604:15)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1246:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.54/mod.js:1026:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.54/mod.js:1244:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1357:14
    at https://deno.land/x/esbuild@v0.14.54/mod.js:658:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.54/mod.js:755:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.54/mod.js:624:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1886:11
Error building D:\temp\silverbullet-main\plugs\markdown\markdown.plug.yaml: Error: Build failed with 1 error:
error: The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/88770189.ts:1:9
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.54/mod.js:1604:15)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1246:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.54/mod.js:1026:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.54/mod.js:1244:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1357:14
    at https://deno.land/x/esbuild@v0.14.54/mod.js:658:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.54/mod.js:755:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.54/mod.js:624:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1886:11
✘ [ERROR] [plugin deno] The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/1ce4b657.ts:1:9

Error building D:\temp\silverbullet-main\plugs\directive\directive.plug.yaml: Error: Build failed with 1 error:
error: The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/1ce4b657.ts:1:9
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.54/mod.js:1604:15)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1246:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.54/mod.js:1026:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.54/mod.js:1244:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1357:14
    at https://deno.land/x/esbuild@v0.14.54/mod.js:658:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.54/mod.js:755:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.54/mod.js:624:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1886:11
✘ [ERROR] [plugin deno] The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/0c179328.ts:1:9

Error building D:\temp\silverbullet-main\plugs\emoji\emoji.plug.yaml: Error: Build failed with 1 error:
error: The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/0c179328.ts:1:9
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.54/mod.js:1604:15)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1246:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.54/mod.js:1026:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.54/mod.js:1244:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1357:14
    at https://deno.land/x/esbuild@v0.14.54/mod.js:658:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.54/mod.js:755:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.54/mod.js:624:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1886:11
✘ [ERROR] [plugin deno] The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/77f62248.ts:1:9

Error building D:\temp\silverbullet-main\plugs\tasks\tasks.plug.yaml: Error: Build failed with 1 error:
error: The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/77f62248.ts:1:9
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.54/mod.js:1604:15)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1246:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.54/mod.js:1026:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.54/mod.js:1244:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1357:14
    at https://deno.land/x/esbuild@v0.14.54/mod.js:658:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.54/mod.js:755:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.54/mod.js:624:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1886:11
✘ [ERROR] [plugin deno] The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/9adb21ca.ts:1:9

Error building D:\temp\silverbullet-main\plugs\core\core.plug.yaml: Error: Build failed with 1 error:
error: The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/9adb21ca.ts:1:9
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.54/mod.js:1604:15)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1246:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.54/mod.js:1026:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.54/mod.js:1244:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1357:14
    at https://deno.land/x/esbuild@v0.14.54/mod.js:658:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.54/mod.js:755:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.54/mod.js:624:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1886:11
✘ [ERROR] [plugin deno] The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/cfcf8a5e.ts:1:9

Error building D:\temp\silverbullet-main\plugs\collab\collab.plug.yaml: Error: Build failed with 1 error:
error: The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/cfcf8a5e.ts:1:9
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.54/mod.js:1604:15)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1246:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.54/mod.js:1026:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.54/mod.js:1244:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1357:14
    at https://deno.land/x/esbuild@v0.14.54/mod.js:658:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.54/mod.js:755:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.54/mod.js:624:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1886:11
✘ [ERROR] [plugin deno] The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/f7971344.ts:1:9

Error building D:\temp\silverbullet-main\plugs\share\share.plug.yaml: Error: Build failed with 1 error:
error: The module's source code could not be parsed: Expected unicode escape at file:///C:/Users/User/AppData/Local/Temp/f7971344.ts:1:9
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.54/mod.js:1604:15)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1246:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.54/mod.js:1026:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.54/mod.js:1244:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1357:14
    at https://deno.land/x/esbuild@v0.14.54/mod.js:658:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.54/mod.js:755:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.54/mod.js:624:7)
    at https://deno.land/x/esbuild@v0.14.54/mod.js:1886:11
Done building plugs in 1095ms
Check file:///D:/temp/silverbullet-main/build.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/yaml.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/parse.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/schema/mod.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/stringify.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/dumper/dumper.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/loader/loader.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/schema/json.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/schema/core.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/schema/extended.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/schema/failsafe.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/schema/default.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/error.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/dumper/dumper_state.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/utils.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/mark.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/loader/loader_state.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/schema.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/mod.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/state.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/bool.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/binary.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/int.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/nil.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/map.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/undefined.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/merge.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/timestamp.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/regexp.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/float.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/str.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/function.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/seq.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/pairs.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/set.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/encoding/_yaml/type/omap.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/io/buffer.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/io/read_lines.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/_util/asserts.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/bytes/copy.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/io/buf_writer.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/io/read_string_delim.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/io/read_delim.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/io/buf_reader.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/bytes/concat.ts
Warning Implicitly using latest version (0.170.0) for https://deno.land/std/bytes/bytes_list.ts
error: Uncaught Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
    await Deno.readTextFile(manifestPath),
    ^
    at async Object.readTextFile (deno:runtime/js/40_read_file.js:56:20)
    at async bundle (file:///D:/temp/silverbullet-main/plugos/bin/plugos-bundle.ts:22:5)
    at async prepareAssets (file:///D:/temp/silverbullet-main/build.ts:50:26)
    at async doBuild (file:///D:/temp/silverbullet-main/build.ts:112:5)
    at async bundle (file:///D:/temp/silverbullet-main/build.ts:68:3)
    at async file:///D:/temp/silverbullet-main/build.ts:126:1
```

**Comment by zefhemel** [comment]
Yeah ok. Let me put this on my list. I can probably fix this fairly quickly once I put my mind to it.

**Comment by zefhemel** [comment]
Alright, I think I fixed it now. Can you give it another shot?
