### ISSUE TITLE
Unable to run application via Podman/Docker

### ISSUE THREAD

**Issue by metahke** [silverbulletmd/silverbullet#1144]
I have run Silverbullet application via deno and everything works fine. I would like to do it with Podman/Docker, but there is an error that I can't resolve. I am following the instructions:

```shell
# Create a local folder "space" to keep files in
mkdir -p space
# Run the SilverBullet docker container in the foreground
sudo docker run -it -p 3000:3000 -v ./space:/space zefhemel/silverbullet
```

I get the following message every time:

```shell
fedora@fedora:~$ mkdir -p space
fedora@fedora:~$ sudo docker run -it -p 3000:3000 -v ./space:/space zefhemel/silverbullet
Will run SilverBullet with UID 1000, inferred from the owner of /space (set PUID environment variable to override)
Running SilverBullet as silverbullet (configured as PUID 1000 and PGID 1000)
```
```js
Unhandled rejection: PromiseRejectionEvent {
  bubbles: false,
  cancelable: true,
  composed: false,
  currentTarget: Window {},
  defaultPrevented: false,
  eventPhase: 2,
  srcElement: null,
  target: Window {},
  returnValue: true,
  timeStamp: 0,
  type: "unhandledrejection",
  promise: Promise {
    <rejected> Error: unable to open database file: /space/.silverbullet.db: Error code 14: Unable to open the database file
    at async Object.openKv (ext:deno_kv/01_db.ts:10:15)
    at async fX (file:///silverbullet.js:2385:13466725)
    at async F.gj [as actionHandler] (file:///silverbullet.js:2385:13468267)
    at async F.execute (file:///silverbullet.js:24:8601)
    at async F.parseCommand (file:///silverbullet.js:24:6314)
    at async file:///silverbullet.js:2418:6541
  },
  reason: Error: unable to open database file: /space/.silverbullet.db: Error code 14: Unable to open the database file
    at async Object.openKv (ext:deno_kv/01_db.ts:10:15)
    at async fX (file:///silverbullet.js:2385:13466725)
    at async F.gj [as actionHandler] (file:///silverbullet.js:2385:13468267)
    at async F.execute (file:///silverbullet.js:24:8601)
    at async F.parseCommand (file:///silverbullet.js:24:6314)
    at async file:///silverbullet.js:2418:6541
}
```

Is there anything else I should do to make the application work with Podman/Docker on my machine?

System: Linux Fedora 41

**Comment by metahke** [comment]
I was able to solve it by adding ":z" to the command after bind mount:
`podman run -it -p 3000:3000 -v ./Documents/Silverbullet:/space:z zefhemel/silverbullet`

❗ **I think this possibility should be explained in the Silverbullet installation instructions. If the app wasn't so great, I would have given up a long time ago.**
