### ISSUE TITLE
SilverBullet behind a reverse proxy doesn't work correctly

### ISSUE THREAD

**Issue by nubblesite** [silverbulletmd/silverbullet#1173]
First, thanks a bunch for this awesome application. I've been using it for documentation related to a software project and so far everything has worked without a hitch minus this one problem that popped up recently. I had my SB running (using Docker) in read-only mode, and also had Watchtower running alongside it. I'm not sure if a container update from Watchtower is what broke it, but at some point my reverse proxy seems to have stopped being able to fully connect to the instance.

When I visit the page using HTTP & the normal IP and port, it loads fine, and works fine. When I access it from my subdomain, it just loads blank with the tab in my browser showing the spinning loading symbol, and none of the buttons at the top do anything - eventually this returns a 504 gateway timed out error:
![image](https://github.com/user-attachments/assets/9374d4fd-551f-4f84-861a-e7e4a81d3ade)

So, thinking that perhaps some files in my previous volume have been corrupted, I spin up a new docker-compose.yml with minimal changes and a new empty folder for the volume:
```
services:
  silverbullet:
    image: zefhemel/silverbullet
    restart: unless-stopped
    environment:
    - SB_USER=admin:password
    - SB_READ_ONLY=false
    - SB_NAME="Documentation"
    volumes:
      - ./new_empty_folder:/space
    ports:
      - 3000:3000
```

When putting this behind my reverse proxy, the same thing happens. I then try accessing the service at the IP:port and it says "refused to connect." The logs show this error:

```   
[...]

Current space index version undefined

Performing a full space reindex, this could take a while...

Indexing SETTINGS page

An exception was thrown as a result of invoking function reindexSpace error: Not found

Unhandled rejection: PromiseRejectionEvent {

  bubbles: false,

  cancelable: true,

  composed: false,

  currentTarget: Window {},

  defaultPrevented: false,

  eventPhase: 2,

  srcElement: null,

  target: Window {},

  returnValue: true,

  timeStamp: 0,

  type: "unhandledrejection",

  promise: Promise {

    <rejected> Error: Not found

    at ry.onMessage (file:///silverbullet.js:89:7948)

    at Worker.worker.onmessage (file:///silverbullet.js:89:7467)

    at Worker.wrappedHandler (ext:deno_web/02_event.js:1400:12)

    at innerInvokeEventListeners (ext:deno_web/02_event.js:757:7)

    at invokeEventListeners (ext:deno_web/02_event.js:804:5)

    at dispatch (ext:deno_web/02_event.js:661:9)

    at Worker.dispatchEvent (ext:deno_web/02_event.js:1041:12)

    at Worker.#pollMessages (ext:runtime/11_workers.js:253:12)

    at eventLoopTick (ext:core/01_core.js:175:7)

  },

  reason: Error: Not found

    at ry.onMessage (file:///silverbullet.js:89:7948)

    at Worker.worker.onmessage (file:///silverbullet.js:89:7467)

    at Worker.wrappedHandler (ext:deno_web/02_event.js:1400:12)

    at innerInvokeEventListeners (ext:deno_web/02_event.js:757:7)

    at invokeEventListeners (ext:deno_web/02_event.js:804:5)

    at dispatch (ext:deno_web/02_event.js:661:9)

    at Worker.dispatchEvent (ext:deno_web/02_event.js:1041:12)

    at Worker.#pollMessages (ext:runtime/11_workers.js:253:12)

    at eventLoopTick (ext:core/01_core.js:175:7)

}
```

**Comment by zefhemel** [comment]
Upon first boot, a SETTINGS.md file should be created in your empty space (I'm guessing it's empty) but that somehow doesn't happen. I see errors around something (presumably the SETTINGS page) not being found. Do you see any permission related issue in the logs, are there any files created in the ./new_empty_folder folder?

**Comment by nubblesite** [comment]
> "504 gateway timed out " means that probably your proxy configuration is wrong, could you pls share it? Also have you checked your proxy logs for any errors?
> 
> This issue is not directly related to silverbullet itself.

I'm using Nginx Proxy Manager, and it doesn't show any logs related to the 504 error unfortunately, just cert renewals. I'll include the configuration below. The reason I suspect SB might be the issue is that ever since this began to happen, I can't even spin up a new SB instance as it gives the error I specified above (it fails to generate a SETTINGS.md file). See the compose file I specified in my original post - I wonder if you are able to replicate the issue?

```
# ------------------------------------------------------------
# my.domain.com
# ------------------------------------------------------------

map $scheme $hsts_header {
    https   "max-age=63072000; preload";
}

server {
  set $forward_scheme http;
  set $server         "siteboss-production";
  set $port           3000;

  listen 80;
  listen [::]:80;

  listen 443 ssl;
  listen [::]:443 ssl;

  server_name my.domain.com;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-59/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-59/privkey.pem;

    # Force SSL
    include conf.d/include/force-ssl.conf;

  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
  proxy_http_version 1.1;

  access_log /data/logs/proxy-host-36_access.log proxy;
  error_log /data/logs/proxy-host-36_error.log warn;

  location / {
    # Access Rules
    allow 10.0.0.1/16;
    allow 192.168.0.1/16;
    deny all;

    # Access checks must...
    satisfy all;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
   
    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}

```

**Comment by Pistahh** [comment]
In your original message you write: "When I visit the page using HTTP & the normal IP and port, it loads fine, and works fine"  - so is it not the case? If it also doesn't run fine without a proxy then it is probably not a proxy issue. If everything is fine without the proxy but not fine using the proxy, then it is likely a proxy issue.

**Comment by nubblesite** [comment]
> In your original message you write: "When I visit the page using HTTP & the normal IP and port, it loads fine, and works fine" - so is it not the case? If it also doesn't run fine without a proxy then it is probably not a proxy issue. If everything is fine without the proxy but not fine using the proxy, then it is likely a proxy issue.

That's right, my SB instance that I spun up alongside Watchtower a month or so ago works when accessed from the IP and port. It worked behind Nginx Proxy Manager for weeks until it suddenly stopped working one day; yes, I agree that the proxy configuration is naturally the first thing to take a look at here, though I've changed nothing about the configuration. I've had [jc21/nginx-proxy-manager](https://github.com/NginxProxyManager/nginx-proxy-manager) running for the past few months uninterrupted and have about 20 other proxy hosts running as well - SilverBullet is the only one that has stopped working. Unfortunately, deleting and recreating the proxy configuration in NPM does not solve the issue. Pointing the proxy configuration to a different application works just fine. I suppose there _could_ be some sneaky bug that's been present in the NPM image for the past few months that has only now reared its head at just my SB proxy configuration, but that seems unlikely to me.

I can't get a new SB instance to initialize correctly on a new AWS instance, on my personal Windows machine or on WSL, or on my actual production server at work - it will not generate SETTINGS.md. So, I think perhaps Watchtower updated my SB container at some point with an image that had a bug introduced that broke the initialization of SETTINGS.md and possibly the proxying as well.

**Comment by nubblesite** [comment]
> In your original message you write: "When I visit the page using HTTP & the normal IP and port, it loads fine, and works fine" - so is it not the case? If it also doesn't run fine without a proxy then it is probably not a proxy issue. If everything is fine without the proxy but not fine using the proxy, then it is likely a proxy issue.

OK, so it looks like the SB_READ_ONLY env variable will prevent SETTINGS.md and index.md from initializing. That explains why my compose file up there didn't work.

My SB instance that I spun up alongside Watchtower a month or so ago works when accessed from the IP and port. It worked behind Nginx Proxy Manager for weeks until it suddenly stopped working one day; yes, I agree that the proxy configuration is naturally the first thing to take a look at here. I've had [jc21/nginx-proxy-manager](https://github.com/NginxProxyManager/nginx-proxy-manager) running for the past few months uninterrupted and have about 20 other proxy hosts running as well - SilverBullet is the only one that has stopped working. Unfortunately, deleting and recreating the proxy configuration in NPM does not solve the issue. Pointing the proxy configuration to a different application works just fine. I suppose there _could_ be some sneaky bug that's been present in the NPM image for the past few months that has only now reared its head at just my SB proxy configuration. If nobody else is able to recreate this behavior with the latest image then I'll chalk it up to buggy NPM or a cosmic bit flip.

**Comment by thebarless** [comment]
@nubblesite, I'm running SB behind NPM without any issue. I have zero configurations entered under Advanced or Custom Locations tabs. All I have set under details is Scheme: http Hostname: <IP> Port: 3000 with an SSL wildcard terminating on NPM and forcing SSL. No other flags are toggled. I recall fighting the configuration setting it up with upstream, etc. but found less is more.

**Comment by nubblesite** [comment]
> [@nubblesite](https://github.com/nubblesite), I'm running SB behind NPM without any issue. I have zero configurations entered under Advanced or Custom Locations tabs. All I have set under details is Scheme: http Hostname: Port: 3000 with an SSL wildcard terminating on NPM and forcing SSL. No other flags are toggled. I recall fighting the configuration setting it up with upstream, etc. but found less is more.

Appreciate the info. So, it turns out that somehow Docker added iptables rules for port 3000 that excluded traffic not coming from the same bridge network. After adding a rule to accept traffic from all networks, it works fine. I guess Docker decided there was some reason to do this suddenly after weeks of running my containers 24/7? Not sure, pretty strange. Closing
