### ISSUE TITLE
404 on update check

### ISSUE THREAD

**Issue by pm64** [silverbulletmd/silverbullet#305]
I've only checked Windows, not sure if this is happening on other platforms. When launching 0.2.6, the following is written to Squirrel-CheckForUpdate.log:

```
[12/01/23 18:23:32] info: Program: Starting Squirrel Updater: --checkForUpdate https://update.electronjs.org/silverbulletmd/silverbullet/win32-x64/0.2.6
[12/01/23 18:23:32] info: Program: Fetching update information, downloading from https://update.electronjs.org/silverbulletmd/silverbullet/win32-x64/0.2.6
[12/01/23 18:23:32] info: CheckForUpdateImpl: Using existing staging user ID: 0af3222e-2fd9-5841-bcd2-be33078c54e4
[12/01/23 18:23:32] info: CheckForUpdateImpl: Downloading RELEASES file from https://update.electronjs.org/silverbulletmd/silverbullet/win32-x64/0.2.6
[12/01/23 18:23:32] info: FileDownloader: Downloading url: https://update.electronjs.org/silverbulletmd/silverbullet/win32-x64/0.2.6/RELEASES?id=silverbullet&localVersion=0.2.6&arch=amd64
[12/01/23 18:23:32] warn: IEnableLogger: Failed to download url: https://update.electronjs.org/silverbulletmd/silverbullet/win32-x64/0.2.6/RELEASES?id=silverbullet&localVersion=0.2.6&arch=amd64: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
[12/01/23 18:23:32] info: FileDownloader: Downloading url: https://update.electronjs.org/silverbulletmd/silverbullet/win32-x64/0.2.6/releases?id=silverbullet&localversion=0.2.6&arch=amd64
[12/01/23 18:23:32] fatal: Finished with unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---
```

**Comment by zefhemel** [comment]
Alright, apparently I removed too many files from the release. Cool, will debug this when I have access to a Windows computer again.

**Comment by zefhemel** [comment]
This should now be fixed, can you verify?
