### ISSUE TITLE
0.2.6 Windows client freezes when pointing to a folder with existing md notes

### ISSUE THREAD

**Issue by rktic** [silverbulletmd/silverbullet#307]
I obviously wanted to know what happens if I'm able to import the markdown files from my existing Obsidian Vault. I can see SB trying to index the files, as the data.db file grows, until it stops. When I restart the app and point it to the same folder again, it seems SB tries to continue indexing. As the db file gets bigger again.

What's the intended behaviour with existing .md files?
And are there any known issues around importing existing ones? Like improperly escaped frontmatter for example?

**Comment by zefhemel** [comment]
Could you run silverbullet.exe from the command line so you get to see the logs and let me know what you get to see there? Alternatively, you can also run the `Debug: Show Logs` command in SB which should show you these logs.

The expected behavior is that upon first launch on a folder without a data.db, it will initiate a full index of all pages. After that, it will index as you go. Right now this doesn't detect new files or changes made outside of SB. A `Space: Reindex` command run wipes the index, and indexes from scratch. 

In general it should always be safe and fine to delete data.db and restart SB to create it from scratch, it's just a data cache.

**Comment by rktic** [comment]
Here's how I crashed it:

```
[Sandbox error] Could not parse frontmatter {
  "mark": {
    "buffer": "title: A few racks for Ableton & Bitwig\nlayout: post\nid: \nfavicon:\ndate: 2009-10-13T20:30:40+00:00\nslug: ableton-bitwig-racks\npermalink: /music-production/ableton-bitwig-racks/\nexcerpt: 'The basic cooking recipe: meant as a starting point, using Ableton Live and a free VST.'\nlayout: post\ncategories:\n  - Music Production\ntags:\n  - Ableton\n  - Bitwig\n\u0000",
    "position": 276,
    "line": 8,
    "column": 0
  },
  "name": "C"
}

```

```
HTTP Server error Error: r.tags.push is not a function
Stack trace: TypeError: r.tags.push is not a function
    at eval (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:2418)
    at f (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:1899)
    at f (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:2002)
    at E (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:2260)
    at D (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:3173)
    at blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:2035
    at l (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:38)
    at blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1648
    at innerInvokeEventListeners (deno:ext/web/02_event.js:775:9)
    at invokeEventListeners (deno:ext/web/02_event.js:815:7)
Stack trace: Error: r.tags.push is not a function
Stack trace: TypeError: r.tags.push is not a function
    at eval (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:2418)
    at f (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:1899)
    at f (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:2002)
    at E (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:2260)
    at D (eval at <anonymous> (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1706), <anonymous>:3:3173)
    at blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:2035
    at l (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:38)
    at blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1648
    at innerInvokeEventListeners (deno:ext/web/02_event.js:775:9)
    at invokeEventListeners (deno:ext/web/02_event.js:815:7)
    at blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:2338
    at l (blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:38)
    at blob:null/31e34ecc-cec9-45ad-9f67-c1dd3ddd964a:1:1648
    at innerInvokeEventListeners (deno:ext/web/02_event.js:775:9)
    at invokeEventListeners (deno:ext/web/02_event.js:815:7)
    at dispatch (deno:ext/web/02_event.js:684:11)
    at dispatchEvent (deno:ext/web/02_event.js:1063:14)
    at pollForMessages (deno:runtime/js/99_main.js:161:9)
    at Sandbox.onMessage (https://get.silverbullet.md/:72455:55)
    at https://get.silverbullet.md/:72556:28
    at safeRun1 (https://get.silverbullet.md/:72359:5)
    at Worker.<anonymous> (https://get.silverbullet.md/:72555:13)
    at innerInvokeEventListeners (deno:ext/web/02_event.js:775:9)
    at invokeEventListeners (deno:ext/web/02_event.js:815:7)
    at dispatch (deno:ext/web/02_event.js:684:11)
    at Worker.dispatchEvent (deno:ext/web/02_event.js:1063:14)
    at Worker.#pollMessages (deno:runtime/js/11_workers.js:197:14)

```

If I restart SB, I get the same errors. At the same time, data.db gains another 100kb.

**Comment by zefhemel** [comment]
That first error about frontmatter shouldn't be breaking, I'm more concerned about the tags.push thing. I just pushed a "robustness" fix for this that may address it. If you're ok installing SB via Deno directly instead of the desktop app, you can try it right now, otherwise for the next desktop release.

**Comment by rktic** [comment]
Of course!

At this point, I need to look up the folder structures of deno installations on Windows. I have the itch of documenting this stuff for others to use. Would it make sense to enable the project wiki for this?

**Comment by zefhemel** [comment]
You can use the install instructions on silverbullet.md. They work on windows too. No need to locally git clone or anything. The version coming from get.silverbullet.md is updated automatically.
