### ISSUE TITLE
SilverBullet crashes on file systems that don't serve file creation dates

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#563]
It gives me this error:
```
Attaching to silverbullet
silverbullet    | Going to start SilverBullet binding to 0.0.0.0:3000
silverbullet    | Running in server-processing mode, keeping state in /space/.silverbullet.db
silverbullet    | Failed to stat /space/SETTINGS.md TypeError: Cannot read properties of null (reading 'getTime')
silverbullet    |     at DiskSpacePrimitives.fetchFileList (file:///silverbullet.js:55341:34)
silverbullet    |     at eventLoopTick (ext:core/01_core.js:183:11)
silverbullet    |     at async AssetBundlePlugSpacePrimitives.fetchFileList (file:///silverbullet.js:53598:19)
silverbullet    |     at async PlugSpacePrimitives.fetchFileList (file:///silverbullet.js:57813:19)
silverbullet    |     at async EventedSpacePrimitives.fetchFileList (file:///silverbullet.js:57680:25)
silverbullet    |     at async ServerSystem.loadPlugs (file:///silverbullet.js:67387:28)
silverbullet    |     at async ServerSystem.init (file:///silverbullet.js:67346:5)
silverbullet    |     at async _Command.serveCommand [as fn] (file:///silverbullet.js:67462:5)
silverbullet    |     at async _Command.execute (file:///silverbullet.js:2930:7)
silverbullet    |     at async file:///silverbullet.js:79638:1
silverbullet    | Loaded plug tasks

silverbullet    | Loading builtins attributes into index
silverbullet    | error: Uncaught (in promise) Error: Could not get meta for SETTINGS.md
silverbullet    |       throw Error(`Could not get meta for ${name}`);
silverbullet    |             ^
silverbullet    |     at DiskSpacePrimitives.getFileMeta (file:///silverbullet.js:55314:13)

```

**Comment by skyrunner15** [comment]
Ran into this same issue all of a sudden today on my Synology NAS.

**Comment by zefhemel** [comment]
@skyrunner15 could you test this by switching to the `zefhemel/silverbullet@edge` image?

**Comment by skyrunner15** [comment]
Edge worked! Prior to that I had to switch back to 0.5.3.

**Comment by zefhemel** [comment]
Thanks for confirming. Preparing a new release now.
