### ISSUE TITLE
"Page: delete" command fails

### ISSUE THREAD

**Issue by tmichela** [silverbulletmd/silverbullet#812]
Deleting a page with the command does not work, with the following error:

```bash
silverbullet-1  | Deleting file Library/Extra/Snippet/taskp.md
silverbullet-1  | An exception was thrown as a result of invoking function showIfEnabled error: Unregistered syscall clientStore.get
silverbullet-1  | Error dispatching event page:deleted to treeview.showIfEnabled: Unregistered syscall clientStore.get
silverbullet-1  | Error deleting attachment Error: Unregistered syscall clientStore.get
silverbullet-1  |     at wa.onMessage (file:///silverbullet.js:117:27964)
silverbullet-1  |     at Worker.worker.onmessage (file:///silverbullet.js:117:27483)
silverbullet-1  |     at Worker.wrappedHandler (ext:deno_web/02_event.js:1401:12)
silverbullet-1  |     at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
silverbullet-1  |     at invokeEventListeners (ext:deno_web/02_event.js:801:5)
silverbullet-1  |     at dispatch (ext:deno_web/02_event.js:658:9)
silverbullet-1  |     at Worker.dispatchEvent (ext:deno_web/02_event.js:1043:12)
silverbullet-1  |     at Worker.#pollMessages (ext:runtime/11_workers.js:258:12)
silverbullet-1  |     at eventLoopTick (ext:core/01_core.js:169:7)
```

**Comment by zefhemel** [comment]
Please upgrade your TreeView plug with `Plugs: Update`

**Comment by zefhemel** [comment]
Cc @joekrill

**Comment by tmichela** [comment]
(but deleting still fails with the treeview plugin updated)

**Comment by zefhemel** [comment]
Ok, yeah @joekrill may have an idea what's going on there.

**Comment by joekrill** [comment]
Sorry all! I'll take a look at this today and try to get a fix out ASAP.
