### ISSUE TITLE
The treeview plugin prevents deleting files in the space

### ISSUE THREAD

**Issue by simone-viozzi** [silverbulletmd/silverbullet#819]
https://github.com/joekrill/silverbullet-treeview/issues/11 happens even if the plugin is removed

```
silverbullet-1  | An exception was thrown as a result of invoking function showIfEnabled error: Unregistered syscall clientStore.get
silverbullet-1  | Error dispatching event page:deleted to treeview.showIfEnabled: Unregistered syscall clientStore.get
silverbullet-1  | Error deleting attachment Error: Unregistered syscall clientStore.get
silverbullet-1  |     at wa.onMessage (file:///silverbullet.js:117:27964)
silverbullet-1  |     at Worker.worker.onmessage (file:///silverbullet.js:117:27483)
silverbullet-1  |     at Worker.wrappedHandler (ext:deno_web/02_event.js:1401:12)
silverbullet-1  |     at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
silverbullet-1  |     at invokeEventListeners (ext:deno_web/02_event.js:801:5)
silverbullet-1  |     at dispatch (ext:deno_web/02_event.js:658:9)
silverbullet-1  |     at Worker.dispatchEvent (ext:deno_web/02_event.js:1043:12)
silverbullet-1  |     at Worker.#pollMessages (ext:runtime/11_workers.js:258:12)
silverbullet-1  |     at eventLoopTick (ext:core/01_core.js:169:7)
```

I tried "reload UI" and others reload commands, clearing browser cache, but the error persists

**Comment by zefhemel** [comment]
Did your remove it from the _plugs folder?

**Comment by simone-viozzi** [comment]
Yes, I launched the command "update plugs", and it removed the js from the _plugs.

**Comment by zefhemel** [comment]
Not what to say, if the file is not there and you restarted the server... There's no caching on the server, so 🤷🏻  Have you tried pointing SilverBullet at an empty folder?

**Comment by hjbout** [comment]
same here, but after restarting the server I could delete the page.

**Comment by simone-viozzi** [comment]
The underlining issue with tree view is now fixed https://github.com/joekrill/silverbullet-treeview/commit/daf7a57e1bc7ea51f0ce00feab6dcd78aa39f7f8
