### ISSUE TITLE
treeview.showIfEnabled error on version 0.7.6

### ISSUE THREAD

**Issue by filcuk** [silverbulletmd/silverbullet#821]
I get the following on boot, the error just keeps repeating and site reports internal server error.
Rolling back to 0.7.5 resolves this.

```
Booting up worker for treeview
An exception was thrown as a result of invoking function showIfEnabled error: Unregistered syscall clientStore.get
Error dispatching event plug:load to treeview.showIfEnabled: Unregistered syscall clientStore.get
Error: Unregistered syscall clientStore.get
    at wa.onMessage (file:///silverbullet.js:117:27964)
    at Worker.worker.onmessage (file:///silverbullet.js:117:27483)
    at Worker.wrappedHandler (ext:deno_web/02_event.js:1401:12)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
    at Worker.dispatchEvent (ext:deno_web/02_event.js:1043:12)
    at Worker.#pollMessages (ext:runtime/11_workers.js:258:12)
    at eventLoopTick (ext:core/01_core.js:169:7)
Booting up worker for index
Error: Unregistered syscall clientStore.get
    at wa.onMessage (file:///silverbullet.js:117:27964)
    at Worker.worker.onmessage (file:///silverbullet.js:117:27483)
    at Worker.wrappedHandler (ext:deno_web/02_event.js:1401:12)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
    at Worker.dispatchEvent (ext:deno_web/02_event.js:1043:12)
    at Worker.#pollMessages (ext:runtime/11_workers.js:258:12)
    at eventLoopTick (ext:core/01_core.js:169:7)
Error: Unregistered syscall clientStore.get
    at wa.onMessage (file:///silverbullet.js:117:27964)
    at Worker.worker.onmessage (file:///silverbullet.js:117:27483)
```

**Comment by filcuk** [comment]
Similar to #819, although the behaviour on my instance is very different (won't load after boot).

**Comment by zefhemel** [comment]
I'll assume this will be fixed after upgrading. If you cannot upgrade because SB doesn't boot:

1. Remove all files from your `_plug` folder in your space
2. Start SilverBullet again
3. Reinstall the treeview plug using the `Plugs: Update` command

**Comment by filcuk** [comment]
Can confirm the above worked, thank you. On latest now.
