### ISSUE TITLE
Setup error: Uncaught TypeError (reading 'deserialize')

### ISSUE THREAD

**Issue by nehege** [silverbulletmd/silverbullet#853]
## Subject

When attempting to set up the project by following the steps outlined in the README, I encounter an error that says: "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'deserialize')". This issue arises immediately after executing the initial commands, preventing further progress in the setup process.

## Environment
* OS: Ubuntu 22.04.4 LTS - 64 bit
* Deno: v1.42.4 (release, x86_64-unknown-linux-gnu)
* Typescript v5.4.3
## Steps to reproduce

```bash
git clone https://github.com/silverbulletmd/silverbullet.git
cd silverbullet
deno task build
deno task install
deno task watch-server
```

## Error stack

```
Check file:///home/user/dev/silverbullet/silverbullet.ts
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'deserialize')
    at h (https://esm.sh/v135/@lezer/lr@1.3.14/X-ZS9AbGV6ZXIvY29tbW9u/es2022/lr.mjs:3:21940)
    at new l (https://esm.sh/v135/@lezer/lr@1.3.14/X-ZS9AbGV6ZXIvY29tbW9u/es2022/lr.mjs:3:22146)
    at Function.deserialize (https://esm.sh/v135/@lezer/lr@1.3.14/X-ZS9AbGV6ZXIvY29tbW9u/es2022/lr.mjs:3:25793)
    at https://esm.sh/v135/@lezer/javascript@1.4.14/X-ZS9AY29kZW1pcnJvci9hdXRvY29tcGxldGUsQGNvZGVtaXJyb3IvbGFuZy1jc3MsQGNvZGVtaXJyb3IvbGFuZ3VhZ2UsQGNvZGVtaXJyb3Ivc3RhdGUsQGxlemVyL2h0bWwsQGxlemVyL2xy/es2022/javascript.mjs:2:4438
```

**Comment by zefhemel** [comment]
Not a great error message, but you need to add a path to a space at the end of that `deno task watch-server` command.

**Comment by nehege** [comment]
I cloned the repository and ran `deno task build`, followed immediately by `deno task test`. However, 8 tests failed, and all of them provided the same error output. Here are the details of the error:

```
error: (in promise) TypeError: Cannot read properties of undefined (reading 'deserialize')
    at h (https://esm.sh/v135/@lezer/lr@1.3.14/X-ZS9AbGV6ZXIvY29tbW9u/es2022/lr.mjs:3:21940)
    at new l (https://esm.sh/v135/@lezer/lr@1.3.14/X-ZS9AbGV6ZXIvY29tbW9u/es2022/lr.mjs:3:22146)
    at Function.deserialize (https://esm.sh/v135/@lezer/lr@1.3.14/X-ZS9AbGV6ZXIvY29tbW9u/es2022/lr.mjs:3:25793)
    at https://esm.sh/v135/@lezer/javascript@1.4.14/X-ZS9AY29kZW1pcnJvci9hdXRvY29tcGxldGUsQGNvZGVtaXJyb3IvbGFuZy1jc3MsQGNvZGVtaXJyb3IvbGFuZ3VhZ2UsQGNvZGVtaXJyb3Ivc3RhdGUsQGxlemVyL2h0bWwsQGxlemVyL2xy/es2022/javascript.mjs:2:4438
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.
```

- Failures:
```
./cmd/test/plug_run.test.ts (uncaught error)
./common/markdown_parser/parser.test.ts (uncaught error)
./plug-api/lib/attribute.test.ts (uncaught error)
./plug-api/lib/feed.test.ts (uncaught error)
./plug-api/lib/parser-query.test.ts (uncaught error)
./plug-api/lib/resolve.test.ts (uncaught error)
./plug-api/lib/tree.test.ts (uncaught error)
./plugs/markdown/markdown_render.test.ts (uncaught error)
```

I assume the issue might be on my end, but I opened this issue just in case. Thank you for your time.

**Comment by zefhemel** [comment]
Right, some dependencies needed to be updated. Should be good now?

**Comment by nehege** [comment]
Great, it is fixed now. Thanks!
